### ISSUE TITLE
Бага на email

### ISSUE THREAD

**Issue by OleksandrIX** [MITIT-DEP22/MititFront#8]
![image](https://github.com/MITIT-DEP22/MititFront/assets/93474880/8571bc62-207c-40b1-80b8-db5afb18b911)
не показую текст в input

**Comment by OleksandrIX** [comment]
![photo_2023-10-14_18-03-31](https://github.com/MITIT-DEP22/MititFront/assets/93474880/e015d9cb-868a-47fc-9420-0b712ebfa32d)

**Comment by UncleTm-07** [comment]
I already fixed this problem!
